[#21] show version admin
maykinmedia/open-api-framework pull request #33
Opened 2024-06-20 09:20 UTC by SonnyBA

2024-06-21 08:00 UTC, stevenbal requested changes
Looks good, just some comments regarding stuff that can be moved to this PR in https://github.com/maykinmedia/objecttypes-api/pull/112

2024-06-21 10:53 UTC, stevenbal commented on open_api_framework/context_processors.py
> +        show_version = bool(url_name not in excluded_version_urls)
Is this necessary? Can't we just check if the user is staff?

2024-06-21 13:46 UTC, SonnyBA commented
This build should pass after merging https://github.com/maykinmedia/open-api-framework/pull/36 (changes for checking the documentation and changes the broken link)

2024-06-27 09:54 UTC, stevenbal approved these changes

2024-06-27 09:55 UTC, merged